# Generated by Django 3.1.4 on 2021-03-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='idata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('temp', models.DecimalField(decimal_places=1, default=25.0, max_digits=3)),
                ('humi', models.DecimalField(decimal_places=1, default=50.0, max_digits=3)),
                ('co2', models.IntegerField(default=1000)),
                ('light', models.IntegerField(default=500)),
                ('fei', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('fei_hint', models.BooleanField(default=False)),
                ('error_hint', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('plant', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('temp_u', models.DecimalField(decimal_places=1, default=25.0, max_digits=3)),
                ('temp_b', models.DecimalField(decimal_places=1, default=20.0, max_digits=3)),
                ('humi_u', models.DecimalField(decimal_places=1, default=90.0, max_digits=3)),
                ('humi_b', models.DecimalField(decimal_places=1, default=50.0, max_digits=3)),
                ('co2_u', models.IntegerField(default=1000)),
                ('co2_b', models.IntegerField(default=0)),
                ('light_u', models.IntegerField(default=500)),
                ('light_b', models.IntegerField(default=10)),
                ('fei_u', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('fei_b', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('user', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('plant', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
