# Generated by Django 3.1.1 on 2020-09-14 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='info',
            new_name='test',
        ),
    ]
