# Generated by Django 3.1.4 on 2021-03-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
    ]
