# Generated by Django 3.1.4 on 2021-03-05 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0002_auto_20210305_2145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='idata',
        ),
    ]
