# Generated by Django 3.1.1 on 2020-09-14 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0002_auto_20200914_1415'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='info',
        ),
    ]
