# Generated by Django 3.1.4 on 2021-03-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0003_delete_idata'),
    ]

    operations = [
        migrations.CreateModel(
            name='idata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('temp', models.DecimalField(decimal_places=1, default=25.0, max_digits=3)),
                ('humi', models.DecimalField(decimal_places=1, default=50.0, max_digits=3)),
                ('co2', models.IntegerField(default=1000)),
                ('light', models.IntegerField(default=500)),
                ('fei', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('fei_hint', models.BooleanField(default=False)),
                ('error_hint', models.IntegerField(default=0)),
            ],
        ),
    ]
