# Generated by Django 3.1.4 on 2021-03-06 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0004_idata'),
    ]

    operations = [
        migrations.AddField(
            model_name='idata',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 14, 6, 58, 245329)),
        ),
    ]
