# Generated by Django 3.1.1 on 2020-09-14 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0005_auto_20200914_1417'),
    ]

    operations = [
        migrations.DeleteModel(
            name='info',
        ),
    ]
