# Generated by Django 3.1.4 on 2021-03-06 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0005_idata_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idata',
            name='id',
        ),
        migrations.AlterField(
            model_name='idata',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 14, 21, 45, 96841), primary_key=True, serialize=False),
        ),
    ]
