# Generated by Django 3.1.1 on 2020-09-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siteapp', '0006_delete_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('plant', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('temp_u', models.IntegerField()),
                ('temp_b', models.IntegerField()),
                ('humi_u', models.IntegerField()),
                ('humi_b', models.IntegerField()),
                ('co2_u', models.IntegerField()),
                ('co2_b', models.IntegerField()),
                ('ischecked', models.BinaryField(max_length=1)),
            ],
        ),
    ]
