# Generated by Django 3.1.4 on 2021-03-23 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0008_auto_20210321_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='url_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='idata',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 10, 22, 28, 102831), primary_key=True, serialize=False),
        ),
    ]
