# Generated by Django 3.1.1 on 2020-11-16 02:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0011_auto_20200915_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='co2_b',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='info',
            name='co2_u',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='info',
            name='humi_b',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='info',
            name='humi_u',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='info',
            name='temp_b',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='info',
            name='temp_u',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
