# Generated by Django 3.1.1 on 2020-11-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0012_auto_20201116_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='co2_b',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='co2_u',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='humi_b',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='humi_u',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='temp_b',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='temp_u',
            field=models.IntegerField(),
        ),
    ]
