# Generated by Django 3.1.4 on 2021-02-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0017_auto_20210124_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='idata',
            fields=[
                ('user', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('temp', models.DecimalField(decimal_places=1, default=25.0, max_digits=3)),
                ('humi', models.DecimalField(decimal_places=1, default=50.0, max_digits=3)),
                ('co2', models.IntegerField(default=1000)),
                ('light', models.IntegerField(default=500)),
                ('fei', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
            ],
        ),
    ]
